return {
    --c# 协议转发
    CLIENT_PLAYER_CURRENCY_CHANGED = "CLIENT_PLAYER_CURRENCY_CHANGED",                           --金币变化
    CLIENT_PLAYER_BINDCURRENCY_CHANGED = "CLIENT_PLAYER_BINDCURRENCY_CHANGED",                   --绑金变化
    CLIENT_PLAYER_DIAMOND_CHANGED = "CLIENT_PLAYER_DIAMOND_CHANGED",                             --钻石变化

    --lua内部消息
    DS_ROOMPLATFORMDETAIL_ACK = "DS_ROOMPLATFORMDETAIL_ACK",                                 --房间台子数据
    DS_SETBETLEVEL_ACK = "DS_SETBETLEVEL_ACK",                                               --押注
    DS_RANDOMRESULT_ACK = "DS_RANDOMRESULT_ACK",                                             --摇奖
    DS_BONUSLOTTERY_ACK = "DS_BONUSLOTTERY_ACK",                                             --抽奖
    DS_GOLDENPOOLCHANGED_NTF = "DS_GOLDENPOOLCHANGED_NTF",                                    --彩金池变化


    DS_ENTER_ROOM_ACK = "DS_ENTER_ROOM_ACK",                                                   --进入房间回应
    DS_GET_READY_ACK = "DS_GET_READY_ACK",
    DS_EXIT_ROOM_ACK = "DS_EXIT_ROOM_ACK",
    DS_PLAYER_JOIN_ACK = "DS_PLAYER_JOIN_ACK",
    DS_PLAYER_LEAVE_ACK = "DS_PLAYER_LEAVE_ACK",
    DS_DISHU_APPEAR_ACK = "DS_DISHU_APPEAR_ACK",
    DS_DISHU_DISAPPEAR_ACK = "DS_DISHU_DISAPPEAR_ACK",
    DS_DISHU_STATE_CHANGE_ACK = "DS_DISHU_STATE_CHANGE_ACK",

    DS_BET_LEVEL_SWITCH_ACK = "DS_BET_LEVEL_SWITCH_ACK",
    DS_BET_LEVEL_CHANGE_ACK = "DS_BET_LEVEL_CHANGE_ACK",
    DS_HIT_ACK = "DS_HIT_ACK",
    DS_OTHER_HIT_ACK = "DS_OTHER_HIT_ACK",
    DS_ITEM_USE_ACK = "DS_ITEM_USE_ACK",
    DS_ITEM_BUY_ACK = "DS_ITEM_BUY_ACK",
    DS_ITEM_COUNT_CHANGE_ACK = "DS_ITEM_COUNT_CHANGE_ACK",
    DS_SEAT_RESOURCE_CHANGE_ACK = "DS_SEAT_RESOURCE_CHANGE_ACK",
    DS_SEAT_ITEM_USED_ACK = "DS_SEAT_ITEM_USED_ACK",
    DS_CRAZY_TIME_START_ACK = "DS_CRAZY_TIME_START_ACK",
    DS_CRAZY_VALUE_CHANGE_ACK = "DS_CRAZY_VALUE_CHANGE_ACK",

    DS_GOLDEN_EGG_ENERGY_CHANGE_ACK = "DS_GOLDEN_EGG_ENERGY_CHANGE_ACK",
    DS_GOLDEN_EGG_START_HIT_ACK = "DS_GOLDEN_EGG_START_HIT_ACK",
    DS_GOLDEN_EGG_HIT_ACK = "DS_GOLDEN_EGG_HIT_ACK",
    DS_GOLDEN_EGG_ENTER_NEXT_STAGE_ACK = "DS_GOLDEN_EGG_ENTER_NEXT_STAGE_ACK",

}
